
package vista;

import javax.swing.JOptionPane;
import java.awt.Dimension;
import java.awt.Toolkit;
/**
 *
 * @author LAB_MOVIL04
 */
public class Panel extends javax.swing.JFrame {

    /**
     * Creates new form panel
     */
    public Panel() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2 - this.getSize().width/2, dim.height/2 - this.getSize().height/2);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        MI_Movimiento = new javax.swing.JMenuItem();
        MI_Usuario = new javax.swing.JMenuItem();
        menuSalir = new javax.swing.JCheckBoxMenuItem();
        menuProductos = new javax.swing.JMenu();
        menuProductosAdmin = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        menuClientes = new javax.swing.JMenu();
        miClientesAdmin = new javax.swing.JMenuItem();
        miClientesAgregar = new javax.swing.JMenuItem();
        miClientesEditar = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        MI_DetalleVenta = new javax.swing.JMenuItem();
        MI_Venta = new javax.swing.JMenuItem();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 385, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 269, Short.MAX_VALUE)
        );

        menuArchivo.setText("Archivos");

        jMenu5.setText("Mantenedores");

        MI_Movimiento.setText("Movimiento");
        MI_Movimiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_MovimientoActionPerformed(evt);
            }
        });
        jMenu5.add(MI_Movimiento);

        MI_Usuario.setText("Usuario");
        MI_Usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_UsuarioActionPerformed(evt);
            }
        });
        jMenu5.add(MI_Usuario);

        menuArchivo.add(jMenu5);

        menuSalir.setSelected(true);
        menuSalir.setText("Salir");
        menuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuSalirActionPerformed(evt);
            }
        });
        menuArchivo.add(menuSalir);

        menuBar.add(menuArchivo);

        menuProductos.setText("Productos");

        menuProductosAdmin.setText("Administrar");
        menuProductosAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuProductosAdminActionPerformed(evt);
            }
        });
        menuProductos.add(menuProductosAdmin);

        jMenuItem1.setText("ProductoPrecio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuProductos.add(jMenuItem1);

        menuBar.add(menuProductos);

        menuClientes.setText("Clientes");

        miClientesAdmin.setText("Clientesadmin");
        miClientesAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClientesAdminActionPerformed(evt);
            }
        });
        menuClientes.add(miClientesAdmin);

        miClientesAgregar.setText("ClientesAgregar");
        miClientesAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miClientesAgregarActionPerformed(evt);
            }
        });
        menuClientes.add(miClientesAgregar);

        miClientesEditar.setText("ClientesEditar");
        menuClientes.add(miClientesEditar);

        menuBar.add(menuClientes);

        jMenu2.setText("Venta");

        MI_DetalleVenta.setText("DetalleVenta");
        MI_DetalleVenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_DetalleVentaActionPerformed(evt);
            }
        });
        jMenu2.add(MI_DetalleVenta);

        MI_Venta.setText("Venta");
        MI_Venta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MI_VentaActionPerformed(evt);
            }
        });
        jMenu2.add(MI_Venta);

        menuBar.add(jMenu2);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(escritorio)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuSalirActionPerformed
    System.exit(0);
        int respuesta = JOptionPane.showConfirmDialog(this, "¿Está seguro/a de queres salir de la aplicación?", "Salir", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        //Si presiona el boton "si", devolverá un 0
        if (respuesta == 0) {
            System.exit(0);
        }
    }//GEN-LAST:event_menuSalirActionPerformed

    private void menuProductosAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProductosAdminActionPerformed
        ProductoAdmin pa = new ProductoAdmin();
        this.escritorio.add(pa);
        pa.setVisible(true);
    }//GEN-LAST:event_menuProductosAdminActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        ProductoPrecio  pp = new ProductoPrecio();
        this.escritorio.add(pp);
        pp.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void miClientesAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClientesAdminActionPerformed
        ClienteAdmin CA = new ClienteAdmin();
        this.escritorio.add(CA);
        CA.setVisible(true);
    }//GEN-LAST:event_miClientesAdminActionPerformed

    private void miClientesAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miClientesAgregarActionPerformed
        ClienteAgregar CAG = new ClienteAgregar();
        this.escritorio.add(CAG);
        CAG.setVisible(true);
        
    }//GEN-LAST:event_miClientesAgregarActionPerformed

    private void MI_DetalleVentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_DetalleVentaActionPerformed
        DetalleVenta DV = new DetalleVenta();
        this.escritorio.add(DV);
        DV.setVisible(true);
    }//GEN-LAST:event_MI_DetalleVentaActionPerformed

    private void MI_VentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_VentaActionPerformed
        Venta V = new Venta();
        this.escritorio.add(V);
        V.setVisible(true);
    }//GEN-LAST:event_MI_VentaActionPerformed

    private void MI_MovimientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_MovimientoActionPerformed
        Movimiento M = new Movimiento();
        this.escritorio.add(M);
        M.setVisible(true);
    }//GEN-LAST:event_MI_MovimientoActionPerformed

    private void MI_UsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MI_UsuarioActionPerformed
        usuario2 U = new usuario2();
        this.escritorio.add(U);
        U.setVisible(true);
    }//GEN-LAST:event_MI_UsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Panel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Panel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MI_DetalleVenta;
    private javax.swing.JMenuItem MI_Movimiento;
    private javax.swing.JMenuItem MI_Usuario;
    private javax.swing.JMenuItem MI_Venta;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuProductos;
    private javax.swing.JMenuItem menuProductosAdmin;
    private javax.swing.JCheckBoxMenuItem menuSalir;
    private javax.swing.JMenuItem miClientesAdmin;
    private javax.swing.JMenuItem miClientesAgregar;
    private javax.swing.JMenuItem miClientesEditar;
    // End of variables declaration//GEN-END:variables
}
